package Vista.NProKumite;

import Vista.Principal;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import modelo.Partido;

public class Kumite extends javax.swing.JDialog {

    private Partido partido;
    private int puntosAzul;
    private int puntosRojo;
    private int centisegundo;
    private int minuto;
    private int segundo;
    private Timer timer;
    private DecimalFormat timeFormatter;

    public Kumite(Principal parent, boolean modal, Partido partido) {
        super(parent, modal);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        initComponents();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        this.partido = partido;
        this.puntosAzul = 0;
        this.puntosRojo = 0;
        this.minuto = 1;
        this.segundo = 30;

        timeFormatter = new DecimalFormat("00");

        timer = new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (centisegundo > 0) {
                    centisegundo--;
                } else {
                    if (segundo == 0 && minuto == 0) {
                        timer.stop();
                    } else if (segundo > 0) {
                        segundo--;
                        centisegundo = 99;
                    } else if (minuto > 0) {
                        minuto--;
                        segundo = 59;
                        centisegundo = 99;
                    }
                }
                setTiempo(minuto, segundo);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP_60Seconds = new javax.swing.JPanel();
        JB_60Seconds = new javax.swing.JButton();
        JP_ResetMatch = new javax.swing.JPanel();
        JB_ResetMatch = new javax.swing.JButton();
        JP_Time = new javax.swing.JPanel();
        JB_ResetTime = new javax.swing.JButton();
        JB_ExtraTime = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JTF_MatchTimeMinute = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JTF_MatchTimeSeconds = new javax.swing.JTextField();
        JP_Close = new javax.swing.JPanel();
        JB_Close = new javax.swing.JButton();
        JB_Start = new javax.swing.JButton();
        JL_PuntajeAzul = new javax.swing.JLabel();
        JL_PuntajeRojo = new javax.swing.JLabel();
        JB_IpponRojo = new javax.swing.JButton();
        JB_WazaAriRojo = new javax.swing.JButton();
        JB_YukoRojo = new javax.swing.JButton();
        JB_IpponAzul = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JB_WazaAriAzul = new javax.swing.JButton();
        JB_YukoAzul = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        JL_Tiempo = new javax.swing.JLabel();
        JCB_SenshuAzul = new javax.swing.JCheckBox();
        JCB_SenshuRojo = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        JCB_HanteiC2Rojo = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        JCB_HanteiC2Azul = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        JCB_HanteiC1Azul = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        JCB_HanteiC1Rojo = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        JL_Fondo = new javax.swing.JLabel();
        JMB_BarraTareas = new javax.swing.JMenuBar();
        JM_Menu = new javax.swing.JMenu();
        JMI_ResetMatch = new javax.swing.JMenuItem();
        JMI_ResetTime = new javax.swing.JMenuItem();
        JMI_ExtraTime = new javax.swing.JMenuItem();
        JMI_60Seconds = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        JMI_About = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        JMI_Close = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("N-Pro Kumite 1.2.2");
        setPreferredSize(new java.awt.Dimension(900, 590));
        setResizable(false);
        getContentPane().setLayout(null);

        JP_60Seconds.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JB_60Seconds.setText("1 Minute");
        JB_60Seconds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_60SecondsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JP_60SecondsLayout = new javax.swing.GroupLayout(JP_60Seconds);
        JP_60Seconds.setLayout(JP_60SecondsLayout);
        JP_60SecondsLayout.setHorizontalGroup(
            JP_60SecondsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_60SecondsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JB_60Seconds, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addContainerGap())
        );
        JP_60SecondsLayout.setVerticalGroup(
            JP_60SecondsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_60SecondsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JB_60Seconds, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(JP_60Seconds);
        JP_60Seconds.setBounds(690, 190, 178, 57);

        JP_ResetMatch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JB_ResetMatch.setText("Reset Match");
        JB_ResetMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ResetMatchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JP_ResetMatchLayout = new javax.swing.GroupLayout(JP_ResetMatch);
        JP_ResetMatch.setLayout(JP_ResetMatchLayout);
        JP_ResetMatchLayout.setHorizontalGroup(
            JP_ResetMatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_ResetMatchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JB_ResetMatch, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addContainerGap())
        );
        JP_ResetMatchLayout.setVerticalGroup(
            JP_ResetMatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_ResetMatchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JB_ResetMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(JP_ResetMatch);
        JP_ResetMatch.setBounds(690, 260, 178, 57);

        JP_Time.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Time"));

        JB_ResetTime.setText("Reset Time");
        JB_ResetTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ResetTimeActionPerformed(evt);
            }
        });

        JB_ExtraTime.setText("Extra Time");
        JB_ExtraTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ExtraTimeActionPerformed(evt);
            }
        });

        jLabel2.setText("Match Time");

        JTF_MatchTimeMinute.setText("1");

        jLabel3.setText(":");

        JTF_MatchTimeSeconds.setText("30");

        javax.swing.GroupLayout JP_TimeLayout = new javax.swing.GroupLayout(JP_Time);
        JP_Time.setLayout(JP_TimeLayout);
        JP_TimeLayout.setHorizontalGroup(
            JP_TimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_TimeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JP_TimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JP_TimeLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTF_MatchTimeMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTF_MatchTimeSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JB_ResetTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JB_ExtraTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JP_TimeLayout.setVerticalGroup(
            JP_TimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_TimeLayout.createSequentialGroup()
                .addComponent(JB_ResetTime, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(JP_TimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTF_MatchTimeMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(JTF_MatchTimeSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_ExtraTime, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(JP_Time);
        JP_Time.setBounds(690, 30, 158, 136);

        JP_Close.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JB_Close.setText("Close");
        JB_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JP_CloseLayout = new javax.swing.GroupLayout(JP_Close);
        JP_Close.setLayout(JP_CloseLayout);
        JP_CloseLayout.setHorizontalGroup(
            JP_CloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_CloseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JB_Close, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addContainerGap())
        );
        JP_CloseLayout.setVerticalGroup(
            JP_CloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_CloseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JB_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(JP_Close);
        JP_Close.setBounds(690, 440, 178, 59);

        JB_Start.setBackground(new java.awt.Color(153, 255, 102));
        JB_Start.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JB_Start.setText("Start");
        JB_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_StartActionPerformed(evt);
            }
        });
        getContentPane().add(JB_Start);
        JB_Start.setBounds(280, 60, 150, 60);

        JL_PuntajeAzul.setFont(new java.awt.Font("Unispace", 1, 48)); // NOI18N
        JL_PuntajeAzul.setForeground(new java.awt.Color(255, 255, 255));
        JL_PuntajeAzul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_PuntajeAzul.setText("0");
        getContentPane().add(JL_PuntajeAzul);
        JL_PuntajeAzul.setBounds(260, 270, 80, 50);

        JL_PuntajeRojo.setFont(new java.awt.Font("Unispace", 1, 48)); // NOI18N
        JL_PuntajeRojo.setForeground(new java.awt.Color(255, 255, 255));
        JL_PuntajeRojo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_PuntajeRojo.setText("0");
        getContentPane().add(JL_PuntajeRojo);
        JL_PuntajeRojo.setBounds(360, 270, 80, 50);

        JB_IpponRojo.setText("Ippon");
        JB_IpponRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_IpponRojoActionPerformed(evt);
            }
        });
        getContentPane().add(JB_IpponRojo);
        JB_IpponRojo.setBounds(520, 50, 130, 30);

        JB_WazaAriRojo.setText("Waza-ari");
        JB_WazaAriRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_WazaAriRojoActionPerformed(evt);
            }
        });
        getContentPane().add(JB_WazaAriRojo);
        JB_WazaAriRojo.setBounds(520, 100, 130, 30);

        JB_YukoRojo.setText("Yuko");
        JB_YukoRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_YukoRojoActionPerformed(evt);
            }
        });
        getContentPane().add(JB_YukoRojo);
        JB_YukoRojo.setBounds(520, 150, 130, 30);

        JB_IpponAzul.setText("Ippon");
        JB_IpponAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_IpponAzulActionPerformed(evt);
            }
        });
        getContentPane().add(JB_IpponAzul);
        JB_IpponAzul.setBounds(40, 50, 130, 30);

        jLabel1.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Category 2");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 430, 170, 32);

        JB_WazaAriAzul.setText("Waza-ari");
        JB_WazaAriAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_WazaAriAzulActionPerformed(evt);
            }
        });
        getContentPane().add(JB_WazaAriAzul);
        JB_WazaAriAzul.setBounds(40, 100, 130, 30);

        JB_YukoAzul.setText("Yuko");
        JB_YukoAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_YukoAzulActionPerformed(evt);
            }
        });
        getContentPane().add(JB_YukoAzul);
        JB_YukoAzul.setBounds(40, 150, 130, 30);

        jLabel4.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Category 1");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(270, 370, 170, 32);

        JL_Tiempo.setFont(new java.awt.Font("Unispace", 1, 48)); // NOI18N
        JL_Tiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_Tiempo.setText("01:30");
        getContentPane().add(JL_Tiempo);
        JL_Tiempo.setBounds(270, 160, 180, 62);

        JCB_SenshuAzul.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        JCB_SenshuAzul.setText("Senshu");
        getContentPane().add(JCB_SenshuAzul);
        JCB_SenshuAzul.setBounds(40, 200, 100, 33);

        JCB_SenshuRojo.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        JCB_SenshuRojo.setText("Senshu");
        JCB_SenshuRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_SenshuRojoActionPerformed(evt);
            }
        });
        getContentPane().add(JCB_SenshuRojo);
        JCB_SenshuRojo.setBounds(550, 200, 87, 33);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        JCB_HanteiC2Rojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_HanteiC2RojoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox2)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox3)
                .addGap(18, 18, 18)
                .addComponent(JCB_HanteiC2Rojo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JCB_HanteiC2Rojo)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox1))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(460, 420, 170, 50);

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        JCB_HanteiC2Azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_HanteiC2AzulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox5)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox6)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox7)
                .addGap(18, 18, 18)
                .addComponent(JCB_HanteiC2Azul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JCB_HanteiC2Azul)
                    .addComponent(jCheckBox7)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox5))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(60, 420, 170, 44);

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        JCB_HanteiC1Azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_HanteiC1AzulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox9)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox10)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox11)
                .addGap(18, 18, 18)
                .addComponent(JCB_HanteiC1Azul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JCB_HanteiC1Azul)
                    .addComponent(jCheckBox11)
                    .addComponent(jCheckBox10)
                    .addComponent(jCheckBox9))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(60, 360, 170, 50);

        jPanel4.setBackground(new java.awt.Color(204, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        JCB_HanteiC1Rojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_HanteiC1RojoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox13)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox14)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox15)
                .addGap(18, 18, 18)
                .addComponent(JCB_HanteiC1Rojo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JCB_HanteiC1Rojo)
                    .addComponent(jCheckBox15)
                    .addComponent(jCheckBox14)
                    .addComponent(jCheckBox13))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(460, 360, 170, 50);

        jLabel5.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("H");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(200, 340, 20, 20);

        jLabel6.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("C");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 340, 20, 20);

        jLabel7.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("K");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 340, 20, 20);

        jLabel8.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("HC");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(150, 340, 30, 20);

        jLabel9.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("C");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(470, 340, 20, 20);

        jLabel10.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("K");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(510, 340, 20, 20);

        jLabel11.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("HC");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(550, 340, 30, 20);

        jLabel12.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("H");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(600, 340, 20, 20);

        jButton1.setText("-1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 280, 43, 23);

        jButton2.setText("-1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(470, 280, 43, 23);

        jCheckBox17.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jCheckBox17.setText("Kiken");
        jCheckBox17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox17ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox17);
        jCheckBox17.setBounds(560, 250, 71, 33);

        jCheckBox18.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jCheckBox18.setText("Kiken");
        jCheckBox18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox18ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox18);
        jCheckBox18.setBounds(40, 250, 71, 33);

        JL_Fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/NProKumite/Fondo.png"))); // NOI18N
        JL_Fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(JL_Fondo);
        JL_Fondo.setBounds(10, 10, 670, 490);

        JM_Menu.setText("Menu");

        JMI_ResetMatch.setText("Reset Match");
        JM_Menu.add(JMI_ResetMatch);

        JMI_ResetTime.setText("Reset Time");
        JM_Menu.add(JMI_ResetTime);

        JMI_ExtraTime.setText("Extra Time");
        JM_Menu.add(JMI_ExtraTime);

        JMI_60Seconds.setText("60 seconds");
        JM_Menu.add(JMI_60Seconds);
        JM_Menu.add(jSeparator3);

        JMI_About.setText("About");
        JM_Menu.add(JMI_About);
        JM_Menu.add(jSeparator4);

        JMI_Close.setText("Close");
        JMI_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_CloseActionPerformed(evt);
            }
        });
        JM_Menu.add(JMI_Close);

        JMB_BarraTareas.add(JM_Menu);

        setJMenuBar(JMB_BarraTareas);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_JB_CloseActionPerformed

    private void JMI_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_CloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_JMI_CloseActionPerformed

    private void JB_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_StartActionPerformed
        if (JB_Start.getText().equalsIgnoreCase("start")) {

            this.timer.start();
            JB_Start.setText("Stop");
        } else {
            this.timer.stop();
            JB_Start.setText("Start");
        }

    }//GEN-LAST:event_JB_StartActionPerformed

    private void JB_60SecondsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_60SecondsActionPerformed
        setTiempo(1, 0);
        this.timer.stop();
    }//GEN-LAST:event_JB_60SecondsActionPerformed

    private void JB_ResetTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ResetTimeActionPerformed
        minuto = Integer.parseInt(JTF_MatchTimeMinute.getText());
        segundo = Integer.parseInt(JTF_MatchTimeSeconds.getText());
        setTiempo(minuto, segundo);
        this.timer.stop();

    }//GEN-LAST:event_JB_ResetTimeActionPerformed

    private void JB_ExtraTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ExtraTimeActionPerformed
        setTiempo(1, 0);
        this.timer.stop();
    }//GEN-LAST:event_JB_ExtraTimeActionPerformed

    private void JB_IpponAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_IpponAzulActionPerformed
        setPuntajeAzul(3);
    }//GEN-LAST:event_JB_IpponAzulActionPerformed

    private void JB_WazaAriAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_WazaAriAzulActionPerformed
        setPuntajeAzul(2);
    }//GEN-LAST:event_JB_WazaAriAzulActionPerformed

    private void JB_YukoAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_YukoAzulActionPerformed
        setPuntajeAzul(1);
    }//GEN-LAST:event_JB_YukoAzulActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setPuntajeAzul(-1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JB_IpponRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_IpponRojoActionPerformed
        setPuntajeRojo(3);
    }//GEN-LAST:event_JB_IpponRojoActionPerformed

    private void JB_WazaAriRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_WazaAriRojoActionPerformed
        setPuntajeRojo(2);
    }//GEN-LAST:event_JB_WazaAriRojoActionPerformed

    private void JB_YukoRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_YukoRojoActionPerformed
        setPuntajeRojo(1);
    }//GEN-LAST:event_JB_YukoRojoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setPuntajeRojo(-1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JCB_HanteiC1AzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_HanteiC1AzulActionPerformed
        JOptionPane.showMessageDialog(this, "Ganador Rojo");
        partido.setGanador(partido.getJugadorB());
        this.dispose();

    }//GEN-LAST:event_JCB_HanteiC1AzulActionPerformed

    private void JCB_HanteiC1RojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_HanteiC1RojoActionPerformed
        JOptionPane.showMessageDialog(this, "Ganador Azul");
        partido.setGanador(partido.getJugadorA());
        this.dispose();
    }//GEN-LAST:event_JCB_HanteiC1RojoActionPerformed

    private void JCB_HanteiC2AzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_HanteiC2AzulActionPerformed
        JOptionPane.showMessageDialog(this, "Ganador Rojo");
        partido.setGanador(partido.getJugadorB());
        this.dispose();
    }//GEN-LAST:event_JCB_HanteiC2AzulActionPerformed

    private void JCB_HanteiC2RojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_HanteiC2RojoActionPerformed
        JOptionPane.showMessageDialog(this, "Ganador Azul");
        partido.setGanador(partido.getJugadorA());
        this.dispose();
    }//GEN-LAST:event_JCB_HanteiC2RojoActionPerformed

    private void JB_ResetMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ResetMatchActionPerformed
        this.dispose();
        Kumite kumite = new Kumite((Principal) this.getParent(), true, this.partido);
        kumite.setVisible(true);
        //Kumite kumite = new Kumite(null);
        //kumite.setVisible(true);
    }//GEN-LAST:event_JB_ResetMatchActionPerformed

    private void jCheckBox17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox17ActionPerformed
        JOptionPane.showMessageDialog(this, "Ganador Azul");
        partido.setGanador(partido.getJugadorB());
        this.dispose();
    }//GEN-LAST:event_jCheckBox17ActionPerformed

    private void jCheckBox18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox18ActionPerformed
        JOptionPane.showMessageDialog(this, "Ganador Rojo");
        partido.setGanador(partido.getJugadorA());
        this.dispose();
    }//GEN-LAST:event_jCheckBox18ActionPerformed

    private void JCB_SenshuRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_SenshuRojoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCB_SenshuRojoActionPerformed

    public void setTiempo(int minuto, int segundo) {
        JL_Tiempo.setText(timeFormatter.format(minuto) + ":"
                + timeFormatter.format(segundo));
        this.minuto = minuto;
        this.segundo = segundo;
    }

    public void setPuntajeAzul(int puntaje) {
        this.puntosAzul += puntaje;
        JL_PuntajeAzul.setText(this.puntosAzul + "");
        if (this.puntosAzul >= 8) {
            JOptionPane.showMessageDialog(this, "Ganador Azul");
            partido.setGanador(partido.getJugadorA());
            this.dispose();
        }
    }

    public void setPuntajeRojo(int puntaje) {
        this.puntosRojo += puntaje;
        JL_PuntajeRojo.setText(this.puntosRojo + "");
        if (this.puntosRojo >= 8) {
            JOptionPane.showMessageDialog(this, "Ganador Rojo");
            partido.setGanador(partido.getJugadorB());
            this.dispose();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_60Seconds;
    private javax.swing.JButton JB_Close;
    private javax.swing.JButton JB_ExtraTime;
    private javax.swing.JButton JB_IpponAzul;
    private javax.swing.JButton JB_IpponRojo;
    private javax.swing.JButton JB_ResetMatch;
    private javax.swing.JButton JB_ResetTime;
    private javax.swing.JButton JB_Start;
    private javax.swing.JButton JB_WazaAriAzul;
    private javax.swing.JButton JB_WazaAriRojo;
    private javax.swing.JButton JB_YukoAzul;
    private javax.swing.JButton JB_YukoRojo;
    private javax.swing.JCheckBox JCB_HanteiC1Azul;
    private javax.swing.JCheckBox JCB_HanteiC1Rojo;
    private javax.swing.JCheckBox JCB_HanteiC2Azul;
    private javax.swing.JCheckBox JCB_HanteiC2Rojo;
    private javax.swing.JCheckBox JCB_SenshuAzul;
    private javax.swing.JCheckBox JCB_SenshuRojo;
    private javax.swing.JLabel JL_Fondo;
    private javax.swing.JLabel JL_PuntajeAzul;
    private javax.swing.JLabel JL_PuntajeRojo;
    private javax.swing.JLabel JL_Tiempo;
    private javax.swing.JMenuBar JMB_BarraTareas;
    private javax.swing.JMenuItem JMI_60Seconds;
    private javax.swing.JMenuItem JMI_About;
    private javax.swing.JMenuItem JMI_Close;
    private javax.swing.JMenuItem JMI_ExtraTime;
    private javax.swing.JMenuItem JMI_ResetMatch;
    private javax.swing.JMenuItem JMI_ResetTime;
    private javax.swing.JMenu JM_Menu;
    private javax.swing.JPanel JP_60Seconds;
    private javax.swing.JPanel JP_Close;
    private javax.swing.JPanel JP_ResetMatch;
    private javax.swing.JPanel JP_Time;
    private javax.swing.JTextField JTF_MatchTimeMinute;
    private javax.swing.JTextField JTF_MatchTimeSeconds;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    // End of variables declaration//GEN-END:variables

}
