package vista;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Jugador;
import modelo.Partido;

public class Byes extends javax.swing.JDialog {

    public Byes(java.awt.Frame parent, boolean modal, ArrayList<Jugador> byes) {
        super(parent, modal);
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        JT_Byes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JT_Byes.setRowSelectionAllowed(true);
        JT_Byes.setColumnSelectionAllowed(false);
        JT_Byes.setDefaultEditor(Object.class, null);
        String col[] = {"Cedula", "Nombre", "Cinturon", "Sexo", "Peso", "Edad", "Estatura"};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        for (Jugador jugador : byes) {
            Object[] objeto = {
                jugador.getCedula(),
                jugador.getNombre_completo(),
                jugador.getCinturon(),
                jugador.getSexo(),
                jugador.getPeso(),
                jugador.getEdad(),
                jugador.getEstatura()
            };
            tableModel.addRow(objeto);
        }
        JT_Byes.setModel(tableModel);
        JT_Byes.getColumnModel().getColumn(0).setPreferredWidth(80);
        JT_Byes.getColumnModel().getColumn(1).setPreferredWidth(100);
        JT_Byes.getColumnModel().getColumn(2).setPreferredWidth(100);
        JT_Byes.getColumnModel().getColumn(3).setPreferredWidth(15);
        JT_Byes.getColumnModel().getColumn(4).setPreferredWidth(15);
        JT_Byes.getColumnModel().getColumn(5).setPreferredWidth(15);
        JT_Byes.getColumnModel().getColumn(6).setPreferredWidth(15);
        JT_Byes.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JT_Byes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JT_Byes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JT_Byes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JT_Byes;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
