package vista;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Jugador;

public class Jugadores extends javax.swing.JDialog {

    public Jugadores(java.awt.Frame parent, boolean modal, ArrayList<Jugador> jugadores) {
        super(parent, modal);
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        JT_Jugadores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JT_Jugadores.setRowSelectionAllowed(true);
        JT_Jugadores.setColumnSelectionAllowed(false);
        JT_Jugadores.setDefaultEditor(Object.class, null);
        String col[] = {"Cedula", "Nombre", "Cinturon", "Sexo", "Peso", "Edad", "Estatura"};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        for (Jugador jugador : jugadores) {
            Object[] objeto = {
                jugador.getCedula(),
                jugador.getNombre_completo(),
                jugador.getCinturon(),
                jugador.getSexo(),
                jugador.getPeso(),
                jugador.getEdad(),
                jugador.getEstatura()
            };
            tableModel.addRow(objeto);
        }
        JT_Jugadores.setModel(tableModel);
        JT_Jugadores.getColumnModel().getColumn(0).setPreferredWidth(80);
        JT_Jugadores.getColumnModel().getColumn(1).setPreferredWidth(100);
        JT_Jugadores.getColumnModel().getColumn(2).setPreferredWidth(100);
        JT_Jugadores.getColumnModel().getColumn(3).setPreferredWidth(15);
        JT_Jugadores.getColumnModel().getColumn(4).setPreferredWidth(15);
        JT_Jugadores.getColumnModel().getColumn(5).setPreferredWidth(15);
        JT_Jugadores.getColumnModel().getColumn(6).setPreferredWidth(15);
        JT_Jugadores.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JT_Jugadores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JT_Jugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Nombre", "Cinturon", "Sexo", "Peso", "Edad", "Estatura"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JT_Jugadores.setColumnSelectionAllowed(true);
        JT_Jugadores.getTableHeader().setResizingAllowed(false);
        JT_Jugadores.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(JT_Jugadores);
        JT_Jugadores.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (JT_Jugadores.getColumnModel().getColumnCount() > 0) {
            JT_Jugadores.getColumnModel().getColumn(0).setResizable(false);
            JT_Jugadores.getColumnModel().getColumn(1).setResizable(false);
            JT_Jugadores.getColumnModel().getColumn(2).setResizable(false);
            JT_Jugadores.getColumnModel().getColumn(3).setResizable(false);
            JT_Jugadores.getColumnModel().getColumn(3).setPreferredWidth(10);
            JT_Jugadores.getColumnModel().getColumn(4).setResizable(false);
            JT_Jugadores.getColumnModel().getColumn(5).setResizable(false);
            JT_Jugadores.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JT_Jugadores;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
