package Vista.Registro;

import com.google.gson.Gson;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import static modelo.CSV.parseLine;
import modelo.Jugador;
import modelo.Torneo;

public class Crear_Torneo_Categoria extends javax.swing.JFrame {

    public Crear_Torneo_Categoria() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_Titutlo = new javax.swing.JLabel();
        JL_Cinturon = new javax.swing.JLabel();
        JL_Sexo = new javax.swing.JLabel();
        JL_Peso = new javax.swing.JLabel();
        JL_Deporte = new javax.swing.JLabel();
        JTF_Peso = new javax.swing.JTextField();
        JB_Guardar = new javax.swing.JButton();
        JL_Edad = new javax.swing.JLabel();
        JTF_Edad = new javax.swing.JTextField();
        JCB_Deporte = new javax.swing.JComboBox<>();
        JCB_Cinturon = new javax.swing.JComboBox<>();
        JL_Kgs = new javax.swing.JLabel();
        JCB_Sexo = new javax.swing.JComboBox<>();
        JL_Años = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nuevo torneo");
        setResizable(false);

        JL_Titutlo.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        JL_Titutlo.setText("Nuevo torneo");

        JL_Cinturon.setText("Cinturon");

        JL_Sexo.setText("Sexo");

        JL_Peso.setText("Peso");

        JL_Deporte.setText("Deporte");

        JTF_Peso.setText("80 a 100");

        JB_Guardar.setText("Guardar y seleccionar archivo excel");
        JB_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_GuardarActionPerformed(evt);
            }
        });

        JL_Edad.setText("Edad");

        JTF_Edad.setText("15 a 20");

        JCB_Deporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KUMITE", "KATA" }));

        JCB_Cinturon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BLANCO", "BLANCO-AMARILLO", "AMARILLO", "AMARILLO-VERDE", "VERDE", "VERDE-AZUL", "AZUL", "AZUL-ROJO", "ROJO", "ROJO-NEGRO" }));

        JL_Kgs.setText("Kg");

        JCB_Sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        JL_Años.setText("Años");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JL_Deporte)
                            .addComponent(JL_Peso)
                            .addComponent(JL_Edad))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JCB_Deporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTF_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JL_Años))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JL_Cinturon)
                            .addComponent(JL_Sexo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(JTF_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JL_Kgs)
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JCB_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JCB_Cinturon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(JB_Guardar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(JL_Titutlo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(JL_Titutlo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_Cinturon)
                    .addComponent(JCB_Cinturon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_Sexo)
                    .addComponent(JCB_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_Peso)
                    .addComponent(JTF_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_Kgs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_Deporte)
                    .addComponent(JCB_Deporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_Edad)
                    .addComponent(JTF_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_Años))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_Guardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_GuardarActionPerformed
        JFileChooser fileChooser = new JFileChooser("../Torneos_csv");
        fileChooser.setFileFilter(new FileNameExtensionFilter("Archivos CSV", "csv"));
        int seleccion = fileChooser.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            try {
                ArrayList<Jugador> jugadores = new ArrayList<>();
                File archivo = fileChooser.getSelectedFile();
                Scanner scanner = new Scanner(archivo);
                while (scanner.hasNext()) {
                    List<String> line = parseLine(scanner.nextLine());
                    if (!line.get(0).equals("Nombre")) {
                        jugadores.add(new Jugador(
                                line.get(0).toUpperCase(),
                                line.get(1), line.get(2),
                                line.get(3),
                                Float.parseFloat(line.get(4)),
                                Integer.parseInt(line.get(5)),
                                Float.parseFloat(line.get(6)))
                        );
                    }
                }
                scanner.close();
                Torneo torneo = new Torneo(jugadores, ((String) this.JCB_Cinturon.getSelectedItem()).toUpperCase(),
                        ((String) this.JCB_Sexo.getSelectedItem()).toUpperCase(), this.JTF_Edad.getText().toUpperCase(),
                        ((String) this.JCB_Deporte.getSelectedItem()).toUpperCase(), this.JTF_Peso.getText().toUpperCase()
                );
                Gson gson = new Gson();
                String json = gson.toJson(torneo);
                fileChooser = new JFileChooser("../Torneos_json");
                if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                    try (PrintWriter out = new PrintWriter(fileChooser.getCurrentDirectory() + "/" + fileChooser.getSelectedFile().getName() + ".json")) {
                        out.println(json);
                    }
                }
                this.dispose();
            } catch (FileNotFoundException ex) {
                System.out.println("[ERROR] Obteniendo el archivo");
            }
        }
    }//GEN-LAST:event_JB_GuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Guardar;
    private javax.swing.JComboBox<String> JCB_Cinturon;
    private javax.swing.JComboBox<String> JCB_Deporte;
    private javax.swing.JComboBox<String> JCB_Sexo;
    private javax.swing.JLabel JL_Años;
    private javax.swing.JLabel JL_Cinturon;
    private javax.swing.JLabel JL_Deporte;
    private javax.swing.JLabel JL_Edad;
    private javax.swing.JLabel JL_Kgs;
    private javax.swing.JLabel JL_Peso;
    private javax.swing.JLabel JL_Sexo;
    private javax.swing.JLabel JL_Titutlo;
    private javax.swing.JTextField JTF_Edad;
    private javax.swing.JTextField JTF_Peso;
    // End of variables declaration//GEN-END:variables
}
